### PR TITLE
Wrong import statement fixed

### PR DESCRIPTION
**Pull request by carlosypunto**

### CODE REVIEW

**Comment by behrang** [comment]
`import Yaml` is correct. Isn't it?

**Comment by carlosypunto** [comment]
Not for me, 
image
I'm using cocoapod

**Comment by behrang** [comment]
I have changed pod file. Can you test again with `1.3`?

It should now work with `import Yaml`.

**Comment by carlosypunto** [comment]
1.3 is not published!
My Podfile is:
```
use_frameworks!
plugin "cocoapods-expert-difficulty"
pod 'YamlSwift'
```

And I get:

```
Using YamlSwift (1.2.1)
```

**Comment by behrang** [comment]
I have change pod dependency from `YamlSwift` to `Yaml`. Please change your dependency and you should be able to see it.

**Comment by behrang** [comment]
Can you verify confirm it is fixed?

**Comment by carlosypunto** [comment]
I believe you need to run this command `pod spec lint; pod trunk push Yaml.podspec`

**Comment by behrang** [comment]
I believe I have done that and I can see Yaml in cocoapods search results.

**Comment by carlosypunto** [comment]
image
but the last version is 1.2.1 not 1.3

**Comment by behrang** [comment]
Search for `Yaml`. I've change pod name to `Yaml`.

**Comment by carlosypunto** [comment]
ok 👍👏 Thanks a lot!

**Comment by behrang** [comment]
Thank you.

**Comment by carlosypunto** [comment]
Your're welcome

**Pull request closed without merging**
