### PR TITLE
Convert to Swift 5

### PR DESCRIPTION
**Pull request by daniel-beard**
- Converts all targets + tests to Swift 5

### CODE REVIEW

**Comment by seivan** [comment]
Thanks!

**Comment by daniel-beard** [comment]
Thanks @seivan! Any chance you could bump the podspec version and publish a new release with these changes?

**Comment by seivan** [comment]
@daniel-beard Sure will get to it later today if that's alright.

**Comment by seivan** [comment]
Seems to be a bug in Cocoapods https://github.com/CocoaPods/CocoaPods/issues/8635 with a potential workaround. 

Generally I recommend Carthage as it's not as intrusive and less broken. Could eventually distribute prebuilt frameworks for all platforms so you'd get faster compile times.

**Comment by daniel-beard** [comment]
@seivan much appreciated, thanks!

**Pull request merged**
