### PR TITLE
Feature/prefix yaml

### PR DESCRIPTION
**Pull request by seivan**
- Rename Result to YAMLResult as Result is such a common case. Internal isn't enough. It can't be nested as its generic. Maybe in Future Swift updates.
- Change project structure in preparation for Swift Package Manager. 
- Make it easier for people to extract relevant source code for inline dependencies

### CODE REVIEW

**Comment by behrang** [comment]
I see that you have moved code under `Sources`. Swift package manager supports a few different styles and one of them doesn't require the `Sources` directory. Is there any reason for this?

**Comment by seivan** [comment]
If you look closer you'll see the YAML folder is void of the public header file and the info plist. It can use be used as a sub module just pointing to the source file.

**Comment by behrang** [comment]
Ok, but now, it seems that module name is changed to `YAML` instead of `Yaml`. Running `swift test` produces:

```
Compile Swift Module 'YamlTests' (2 sources)
/Users/behrang/Desktop/YamlSwift/Tests/YamlTests/ExampleTests.swift:1:8: error: cannot load module 'YAML' as 'Yaml'
import Yaml
       ^
/Users/behrang/Desktop/YamlSwift/Tests/YamlTests/ExampleTests.swift:1:8: error: cannot load module 'YAML' as 'Yaml'
import Yaml
       ^
```

**Comment by behrang** [comment]
Oh, it was not supposed to be tested with swift package manager. Can we fix it all in this PR?

**Comment by seivan** [comment]
@behrang Did running tests with Swift package manager work in master? It was never my intention to  add those if that wasn't the case. 

This PR makes it easier to import YamlSwift as inline through submodules by

1.  Prefixing Result with YAML
2. Isolating actual source code from project code. 

That's the only thing this PR does. 
However, you're saying it has broken `$ swift test` ?

**Comment by behrang** [comment]
No, it hasn't. I'm saying it is better to migrate it in one step and add swift package manager compatibility too.

**Comment by seivan** [comment]
I suggest doing it in two steps so at least we can confirm that each works independent of each other. You Ok with that?

**Comment by behrang** [comment]
Ok, merged.

**Pull request merged**
