### PR TITLE
Support Swift 2.3

### PR DESCRIPTION
**Pull request by norio-nomura**
- Run convert to current Swift syntax using Swift 2.3
  - No codes are changed.
  - LastSwiftMigration on each targets
  - `SWIFT_VERSION = 2.3`
- Update project settings to recommended settings of Xcode 8 beta 1
- Add `SWIFT_VERSION` xcconfig to podspec

### CODE REVIEW

**Comment by behrang** [comment]
Thanks

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Comment by ikesyo** [comment]
It would be helpful if we get 1.4.4 or 1.5.0 release which supports Swift 2.3 with this fix. :pray:

**Comment by behrang** [comment]
Ok, 1.5.0 released.

**Comment by ikesyo** [comment]
That's great! Thanks for the quick reply 😄

**Comment by behrang** [comment]
You're welcome.

**Pull request merged**
