### PR TITLE
Using Xcode9 and Swift 4. 

### PR DESCRIPTION
**Pull request by seivan**
* `Context` will no use `String.SubSequence` as keys instead of `String`.

### CODE REVIEW

**Comment by behrang** [comment]
Hey, I can't maintain this project anymore. Do you want me to add you as a collaborator for now, so you can go on with the maintenance?

**Comment by seivan** [comment]
@behrang That's fine. I am still coming to grasp with the code base but I don't completely get everything yet. 

On a side note, I actually think it would be nice to make a Parsec implementation in Swift and then use that to write a YAML parser. We actually use our own home made shitty Parsec implementation to parse the content of the YAML structure into an AST. 

Have you looked into making a start on a Parsec implementation?

**Comment by behrang** [comment]
You're right. In fact, I have created a Parsec implementation last year (https://github.com/behrang/SwiftParsec), and implemented Yaml over it (on the `parsec` branch of this project), and it is complete, but a little slower performance wise. If you can, I would like to add you as a collaborator of that project too.

**Comment by seivan** [comment]
@behrang Not yet, let me learn and figure things out until I jump on that 👍 
I am actually looking into learning to implement it myself first. 

Thanks! 🍺

**Comment by behrang** [comment]
Ok, if you were interested, let me know. Thanks.

**Pull request merged**
