### PR TITLE
Swift 3 & Linux support (not for merging)

### PR DESCRIPTION
**Pull request by jpsim**
This isn't for merging but rather to start a conversation about how (if) you want to support Linux or Swift 3. The disabled tests are due to [SR-1674](https://bugs.swift.org/browse/SR-1674).

### CODE REVIEW

**Comment by jpsim** [comment]
By the way, here are the steps you can take to test this out on a fresh Ubuntu 15.10 installation:

```
$ apt-get install curl git clang libicu-dev
$ eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
$ swiftenv install DEVELOPMENT-SNAPSHOT-2016-05-31-a
$ git clone https://github.com/jpsim/YamlSwift.git
$ cd YamlSwift
$ git checkout jp-linux 
$ swift build
$ swift test
```

**Comment by behrang** [comment]
Thanks for your help on this library. Since you are working on this, I wanted to let you know what are my plans.

I started this library for learning Swift. In the process, I changed it from an imperative style to a functional style. After release, I learned a little bit about parsers and I figured out that this is a bad design for this library. Currently, I'm working on a parser combinator library, written in Swift, and I hope to publish it in a few days. It is working and just needs a little more polish. With that, I want to try to write another version of this library which would be a lot simpler to maintain.

**Comment by jpsim** [comment]
Ah, that sounds quite fascinating! I look forward to seeing that :smile:

**Comment by behrang** [comment]
It took a little longer, but it is ready. If you are interested, you can find it here: https://github.com/behrang/SwiftParsec.

**Comment by jpsim** [comment]
Looks great!

**Comment by jpsim** [comment]
@behrang not to push your generosity with this project, but do you still expect to write another version of this library with Parsec?

**Comment by behrang** [comment]
Currently I'm working on it. In the mean time, if merging this branch or making some minor changes helps, let me know.

One thing that I need help with is a bug in Swift which I hadn't report and I'm not sure it will be fixed. If you can, help me with that. It is in this code in JSON example in SwiftParsec:

```js
func array () -> StringParser<Json>.T {
  // the next line crashes the compiler with "Segmentation fault: 11"
  // return between(leftBracket(), rightBracket(), sepBy(value(), comma()))
  //     >>- { js in create(.array(js)) }
  // as a result, we can't have an array within an array for now
  func element () -> StringParser<Json>.T {
    return null() <|> bool() <|> number() <|> str() <|> object()
  }
  return between(leftBracket(), rightBracket(), sepBy(element(), comma()))
      >>- { js in create(.array(js)) }
      <?> "array"
}
```

**Comment by jpsim** [comment]
@behrang what would you like to do for Swift 3? Xcode 8 is now out of beta. Is the goal still to migrate to Parsec? This branch still works with Xcode 8 GM, by the way.

**Comment by behrang** [comment]
I'm working on the Parsec branch. Until that branch is ready, this one should be used. I'll merge it.

**Comment by behrang** [comment]
@jpsim Can you check it to see if it is ok? If it is, I'll bump version.

**Comment by jpsim** [comment]
Yes it's ok, other than the failing tests I disabled.

**Comment by behrang** [comment]
Ok, 1.4.4 released.

**Comment by ikesyo** [comment]
Having breaking changes in a patch version is not ideal I think. 😅

**Comment by behrang** [comment]
Sorry. My bad. Removed the tag and bump major version. Thanks for reminding it.

**Pull request merged**
