### PR TITLE
Encapsulation and Swift_3_guidelines

### PR DESCRIPTION
**Pull request by seivan**
This also contains https://github.com/behrang/YamlSwift/pull/37
I made two separate PR in case this is too much of a change.

* Moved  `-` and `==` operator to be defined inside `Yaml`.
* Switching all enums to be lowercase. Using `_` prefix on keywords like '_true' and '_false'.
* Encapsulated `Context` under `Yaml`
* Created an `internal`struct `Regex`, encapsulated under `Yaml` with three internal static functions. The rest of the code in `Regex.swift` are `private`
* Made Result<T> internal instead of public as you can't nest generic types. 
* Renamed files using `YAML` Prefix. This helps when using in-project source instead of frameworks. 
* `Yaml` static functions now throw a `ResultError` instead of returning a `Result<T>` monad.
* Moving everything that is used in a single scope to `private` and single files to `fileprivate`
* The rest are moved into static functions nested under Yaml -> <Struct>
* Added a `.travis.yml` file to run iOS Scheme for now, will add others some other time.
* Updated Readme to reflect API changes. 

I made Result<T> internal, and changed the public functions to throw an error (idiomatic Swift) instead of returning a monad. I know that's a significant change, but even if I do personally prefer monads and Result<T> works like an optional (which is also a monad), I'd think it would suit more people with throwable functions.

### CODE REVIEW

**Comment by behrang** [comment]
Ok, this is great, thanks a lot. Can I ask you to update Readme too?

**Comment by seivan** [comment]
@behrang  I'm on it. Sorry.

**Comment by behrang** [comment]
Also, isn't `YamlParser` more readable than `YAMLParser`?

**Comment by seivan** [comment]
Yep `YamlParser` is more readable, but this isn't code and `YAMLParser` is the name of the file to hi-light a prefix. 

Some old convention from the obj-c world were you'd prefix with capital letters.

**Comment by seivan** [comment]
@behrang How about now, good?

**Comment by seivan** [comment]
If the changes in this PR is okay, you can go ahead and close down https://github.com/behrang/YamlSwift/pull/37 that only contains the enum changes and nothing more.

**Comment by behrang** [comment]
Excelent. Thanks for your great work.

**Comment by behrang** [comment]
Bumped version to `3.0.0`.

**Pull request merged**
